# This rule is not used by the project kmcp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kagent.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kmcp
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-admin-role
rules:
- apiGroups:
  - kagent.dev
  resources:
  - mcpservers
  verbs:
  - '*'
- apiGroups:
  - kagent.dev
  resources:
  - mcpservers/status
  verbs:
  - get
