---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kagent.dev
  resources:
  - mcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kagent.dev
  resources:
  - mcpservers/finalizers
  verbs:
  - update
- apiGroups:
  - kagent.dev
  resources:
  - mcpservers/status
  verbs:
  - get
  - patch
  - update
