apiVersion: v1
data:
  local.yaml: |
    binds:
    - listeners:
      - name: default
        protocol: HTTP
        routes:
        - backends:
          - backend:
              mcp:
                name: test-stdio-server
                targets:
                - name: test-stdio-server
                  spec:
                    stdio:
                      args:
                      - -y
                      - '@modelcontextprotocol/server-filesystem'
                      - /
                      cmd: npx
            weight: 100
          matches:
          - path:
              pathPrefix: /sse
          - path:
              pathPrefix: /mcp
          name: mcp
      port: 3000
    config: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test-stdio-server
  namespace: default
