apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: test-http-server
  namespace: default
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: test-http-server
    app.kubernetes.io/name: test-http-server
status:
  loadBalancer: {}
