apiVersion: v1
data:
  local.yaml: |
    binds:
    - listeners:
      - name: default
        protocol: HTTP
        routes:
        - backends:
          - backend:
              mcp:
                name: test-http-server
                targets:
                - name: test-http-server
                  spec:
                    stdio:
                      args:
                      - run
                      - start:streamableHttp
                      cmd: npm
            weight: 100
          matches:
          - path:
              pathPrefix: /sse
          - path:
              pathPrefix: /mcp
          name: mcp
      port: 3001
    config: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test-http-server
  namespace: default
