---
# Example MCPServer with ServiceAccount configuration for AWS IRSA
# This demonstrates how to configure annotations and labels on the
# ServiceAccount created by the MCPServer controller.
#
# Use case: AWS IRSA (IAM Roles for Service Accounts) authentication
# The eks.amazonaws.com/role-arn annotation allows pods using this
# ServiceAccount to assume an IAM role without requiring AWS credentials.
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcpserver-irsa-example
  namespace: default
spec:
  deployment:
    image: ghcr.io/modelcontextprotocol/servers/filesystem:latest
    port: 3000
    cmd: /usr/local/bin/mcp-server-filesystem
    args:
      - /data
    # ServiceAccount configuration for AWS IRSA
    serviceAccount:
      annotations:
        # AWS IRSA annotation - replace with your IAM role ARN
        eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/my-mcp-server-role"
        # Optional: use regional STS endpoints
        eks.amazonaws.com/sts-regional-endpoints: "true"
      labels:
        # Custom labels for organization and policy enforcement
        team: platform
        component: mcp-server
        environment: production
        managed-by: kmcp
  transportType: stdio
  stdioTransport: {}
