//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTransport) DeepCopyInto(out *HTTPTransport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTransport.
func (in *HTTPTransport) DeepCopy() *HTTPTransport {
	if in == nil {
		return nil
	}
	out := new(HTTPTransport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakProvider) DeepCopyInto(out *KeycloakProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakProvider.
func (in *KeycloakProvider) DeepCopy() *KeycloakProvider {
	if in == nil {
		return nil
	}
	out := new(KeycloakProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAuthorizationServer) DeepCopyInto(out *MCPAuthorizationServer) {
	*out = *in
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(MCPClientProvider)
		**out = **in
	}
	in.ResourceMetadata.DeepCopyInto(&out.ResourceMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAuthorizationServer.
func (in *MCPAuthorizationServer) DeepCopy() *MCPAuthorizationServer {
	if in == nil {
		return nil
	}
	out := new(MCPAuthorizationServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPClientProvider) DeepCopyInto(out *MCPClientProvider) {
	*out = *in
	out.Keycloak = in.Keycloak
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPClientProvider.
func (in *MCPClientProvider) DeepCopy() *MCPClientProvider {
	if in == nil {
		return nil
	}
	out := new(MCPClientProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPClientResourceMetadata) DeepCopyInto(out *MCPClientResourceMetadata) {
	*out = *in
	if in.ScopesSupported != nil {
		in, out := &in.ScopesSupported, &out.ScopesSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BearerMethodsSupported != nil {
		in, out := &in.BearerMethodsSupported, &out.BearerMethodsSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalFields != nil {
		in, out := &in.AdditionalFields, &out.AdditionalFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPClientResourceMetadata.
func (in *MCPClientResourceMetadata) DeepCopy() *MCPClientResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(MCPClientResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerAuthentication) DeepCopyInto(out *MCPServerAuthentication) {
	*out = *in
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(MCPServerJWTAuthentication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerAuthentication.
func (in *MCPServerAuthentication) DeepCopy() *MCPServerAuthentication {
	if in == nil {
		return nil
	}
	out := new(MCPServerAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerAuthorization) DeepCopyInto(out *MCPServerAuthorization) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(MCPAuthorizationServer)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerAuthorization.
func (in *MCPServerAuthorization) DeepCopy() *MCPServerAuthorization {
	if in == nil {
		return nil
	}
	out := new(MCPServerAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDeployment) DeepCopyInto(out *MCPServerDeployment) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDeployment.
func (in *MCPServerDeployment) DeepCopy() *MCPServerDeployment {
	if in == nil {
		return nil
	}
	out := new(MCPServerDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerJWTAuthentication) DeepCopyInto(out *MCPServerJWTAuthentication) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JWKS != nil {
		in, out := &in.JWKS, &out.JWKS
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerJWTAuthentication.
func (in *MCPServerJWTAuthentication) DeepCopy() *MCPServerJWTAuthentication {
	if in == nil {
		return nil
	}
	out := new(MCPServerJWTAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerList) DeepCopyInto(out *MCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerList.
func (in *MCPServerList) DeepCopy() *MCPServerList {
	if in == nil {
		return nil
	}
	out := new(MCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	if in.StdioTransport != nil {
		in, out := &in.StdioTransport, &out.StdioTransport
		*out = new(StdioTransport)
		**out = **in
	}
	if in.HTTPTransport != nil {
		in, out := &in.HTTPTransport, &out.HTTPTransport
		*out = new(HTTPTransport)
		**out = **in
	}
	if in.Authn != nil {
		in, out := &in.Authn, &out.Authn
		*out = new(MCPServerAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.Authz != nil {
		in, out := &in.Authz, &out.Authz
		*out = new(MCPServerAuthorization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StdioTransport) DeepCopyInto(out *StdioTransport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StdioTransport.
func (in *StdioTransport) DeepCopy() *StdioTransport {
	if in == nil {
		return nil
	}
	out := new(StdioTransport)
	in.DeepCopyInto(out)
	return out
}
