{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kmcp.fullname" . }}-controller-rolebinding
  labels:
    {{- include "kmcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kmcp.fullname" . }}-controller-role
subjects:
- kind: ServiceAccount
  name: {{ include "kmcp.fullname" . }}-controller
  namespace: {{ include "kmcp.namespace" . }}
{{- end }} 