{{- if .Values.rbac.create }}
{{- if .Values.controller.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kmcp.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "kmcp.namespace" . }}
  labels:
    {{- include "kmcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kmcp.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kmcp.serviceAccountName" . }}
  namespace: {{ include "kmcp.namespace" . }}
{{- end }}
{{- end }} 