{{- if .Values.rbac.create }}
{{- if .Values.controller.metrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-metrics-auth-rolebinding
  labels:
    {{- include "kmcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "kmcp.serviceAccountName" . }}
  namespace: {{ include "kmcp.namespace" . }}
{{- end }}
{{- end }} 