apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server-with-auth
  namespace: default
spec:
  deployment:
    image: mcp/everything
    port: 3000
    cmd: npx
    args:
      - "-y"
      - "@modelcontextprotocol/server-github"
  transportType: stdio
  pathMatch:
    - exact: "/keycloak/mcp"
    - exact: "/.well-known/oauth-protected-resource/keycloak/mcp"
    - exact: "/.well-known/oauth-authorization-server/keycloak/mcp"
    - exact: "/.well-known/oauth-authorization-server/keycloak/mcp/client-registration"
    - exact: "/realms/mcp/protocol/openid-connect/certs"
  routeFilter:
    cors:
      allowHeaders:
        - mcp-protocol-version
        - content-type
      allowOrigins:
        - '*'
  authzServer:
    issuer: "http://keycloak.default.svc.cluster.local:8080/realms/mcp"
    jwksUrl: "http://keycloak.default.svc.cluster.local:8080/realms/mcp/protocol/openid-connect/certs"
    audience: "mcp_proxy"
    provider:
      keycloak: {}
    resourceMetadata:
      resource: "http://localhost:3000/keycloak/mcp"
      scopesSupported:
      - "read:all"
      bearerMethodsSupported:
      - "header"
      - "body"
      - "query"
      additionalFields:
        resourceDocumentation: "http://localhost:3000/keycloak/docs"
        resourcePolicyUri: "http://localhost:3000/keycloak/policies"
