apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-mcp-server-with-auth
  namespace: default
spec:
  deployment:
    image: mcp/everything
    port: 3000
    cmd: npx
    args:
      - "-y"
      - "@modelcontextprotocol/server-github"
  transportType: stdio
  routeFilter:
    cors:
      allowHeaders:
        - mcp-protocol-version
        - content-type
      allowOrigins:
        - '*'
  authz:
    server:
      issuer: "http://keycloak.default.svc.cluster.local:8080/realms/mcp"
      jwksUrl: "http://keycloak.default.svc.cluster.local:8080/realms/mcp/protocol/openid-connect/certs"
      audience: "mcp_proxy"
      provider:
        keycloak: {}
      resourceMetadata:
        baseUrl: "http://localhost:3000"
        scopesSupported:
        - "read:all"
        bearerMethodsSupported:
        - "header"
        - "body"
        - "query"
